In [1]:
import pandas as pd
import numpy as np

In [3]:
import matplotlib.pyplot as plt # Import matplotlib for data visualisation
import seaborn as sns

In [16]:
%pip install xlrd>=2.0.1

emission = pd.read_excel(r"C:\Users\Hp\Downloads\Carbon emission dataset.xls")

[notice] A new release of pip is available: 25.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.

In [18]:
emission

,Country code,Country name,Series code,Series name,SCALE,Decimals,1990,1991,1992,1993,...,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011
0,ABW,Aruba,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,29.57481,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1,ADO,Andorra,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,0,..,..,..,...,..,..,..,..,..,..,..,..,..,..
2,AFG,Afghanistan,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,0,..,..,..,...,..,..,..,..,..,..,..,..,..,..
3,AGO,Angola,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,0.208235,..,..,..,...,..,..,..,..,..,..,..,..,..,..
4,ALB,Albania,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,4.967875,..,..,..,...,..,..,..,..,..,..,..,..,..,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13507,YEM,"Yemen, Rep.",SP.URB.TOTL,Urban population,0,0,2497175.681,2693642.2632,2909756.3552,3139637.3184,...,5148619.3146,5410331.206,5683412.0046,5967457.827,6275723.036,6597265.194,6932788.708,7283068.4108,7648699.452,..
13508,ZAF,South Africa,SP.URB.TOTL,Urban population,0,0,18304000,18864881.576074,19446091.545173,20048481.072485,...,26345562.7512,26904362.5996,27448218.3022,27988692.117,28533559.5188,29079838.1332,29636881.5628,30193795.83,30844632.1,..
13509,ZAR,"Congo, Dem. Rep.",SP.URB.TOTL,Urban population,0,0,10120930.828,10569454.3904,11060046.8476,11568627.5584,...,16125336.2688,16867832.791,17640845.614,18431987.562,19333729.388,20261443.145,21216476.3796,22201848.3232,23219959.84,..
13510,ZMB,Zambia,SP.URB.TOTL,Urban population,0,0,3096860.882,3141668.2968,3183257.2304,3223514.6742,...,3729882.6848,3819640.7412,3912870.7312,4011827.75,4128986.897,4253139.4752,4384858.5704,4524564.0776,4614728.013,..
13511,ZWE,Zimbabwe,SP.URB.TOTL,Urban population,0,0,3036068.58,3175022.711,3310511.552,3443081.8224,...,4367338.8024,4422102.3736,4469726.7596,4512876.274,4558288.489,4600586.907,4649406.1562,4717663.7744,4814866.882,..

In [19]:
emission.keys()

Index(['Country code', 'Country name',  'Series code',  'Series name',
              'SCALE',     'Decimals',           1990,           1991,
                 1992,           1993,           1994,           1995,
                 1996,           1997,           1998,           1999,
                 2000,           2001,           2002,           2003,
                 2004,           2005,           2006,           2007,
                 2008,           2009,           2010,           2011],
      dtype='object')

In [22]:
print(emission['Country name'])

0                   Aruba
1                 Andorra
2             Afghanistan
3                  Angola
4                 Albania
               ...
13507         Yemen, Rep.
13508        South Africa
13509    Congo, Dem. Rep.
13510              Zambia
13511            Zimbabwe
Name: Country name, Length: 13512, dtype: object

In [23]:
emission.head(5)

,Country code,Country name,Series code,Series name,SCALE,Decimals,1990,1991,1992,1993,...,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011
0,ABW,Aruba,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,29.57481,..,..,..,...,..,..,..,..,..,..,..,..,..,..
1,ADO,Andorra,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,0,..,..,..,...,..,..,..,..,..,..,..,..,..,..
2,AFG,Afghanistan,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,0,..,..,..,...,..,..,..,..,..,..,..,..,..,..
3,AGO,Angola,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,0.208235,..,..,..,...,..,..,..,..,..,..,..,..,..,..
4,ALB,Albania,AG.LND.EL5M.ZS,Land area below 5m (% of land area),0,1,4.967875,..,..,..,...,..,..,..,..,..,..,..,..,..,..

In [24]:
emission.tail(5)

,Country code,Country name,Series code,Series name,SCALE,Decimals,1990,1991,1992,1993,...,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011
13507,YEM,"Yemen, Rep.",SP.URB.TOTL,Urban population,0,0,2497175.681,2693642.2632,2909756.3552,3139637.3184,...,5148619.3146,5410331.206,5683412.0046,5967457.827,6275723.036,6597265.194,6932788.708,7283068.4108,7648699.452,..
13508,ZAF,South Africa,SP.URB.TOTL,Urban population,0,0,18304000,18864881.576074,19446091.545173,20048481.072485,...,26345562.7512,26904362.5996,27448218.3022,27988692.117,28533559.5188,29079838.1332,29636881.5628,30193795.83,30844632.1,..
13509,ZAR,"Congo, Dem. Rep.",SP.URB.TOTL,Urban population,0,0,10120930.828,10569454.3904,11060046.8476,11568627.5584,...,16125336.2688,16867832.791,17640845.614,18431987.562,19333729.388,20261443.145,21216476.3796,22201848.3232,23219959.84,..
13510,ZMB,Zambia,SP.URB.TOTL,Urban population,0,0,3096860.882,3141668.2968,3183257.2304,3223514.6742,...,3729882.6848,3819640.7412,3912870.7312,4011827.75,4128986.897,4253139.4752,4384858.5704,4524564.0776,4614728.013,..
13511,ZWE,Zimbabwe,SP.URB.TOTL,Urban population,0,0,3036068.58,3175022.711,3310511.552,3443081.8224,...,4367338.8024,4422102.3736,4469726.7596,4512876.274,4558288.489,4600586.907,4649406.1562,4717663.7744,4814866.882,..